server {
    listen 80;
    server_name localhost;

    # Directorio donde se compila la app de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Evita errores 404 al recargar rutas de react-router
    }

    # Redirección interna y limpia hacia el contenedor del backend
    location /api {
        proxy_pass http://backend-api:4005; # 'backend-api' será el nombre del servicio en docker-compose
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Redirección opcional para la documentación de Swagger si deseas verla desde el dominio principal
    location /docs {
        proxy_pass http://backend-api:4005/docs;
        proxy_set_header Host $host;
    }
}