version: '3.8'

services:
  backend-api:
    build:
      context: ./herramientas-node-api
      dockerfile: Dockerfile
    container_name: herramientas_backend
    environment:
      - PORT=4005
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    # No exponemos puertos al host para cumplir con la regla de seguridad del enunciado
    restart: always

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: herramientas_frontend
    depends_on:
      - backend-api
    ports:
      - "80:80" # Coolify leerá este puerto público para asignarle tu dominio
    restart: always